complexity:
  LongMethod:
    threshold: 100
    ignoreAnnotated: [ 'Composable' ]
  CyclomaticComplexMethod:
    ignoreAnnotated: [ 'Composable' ]
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  ComplexCondition:
    threshold: 7

performance:
  SpreadOperator:
    active: false

formatting:
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
  ImportOrdering:
    active: false
  MaximumLineLength:
    maxLineLength: 150
  Indentation:
    active: false
  Filename:
    active: false
  PackageName:
    active: false
  ArgumentListWrapping:
    maxLineLength: 150

style:
  MagicNumber:
    active: false
    ignoreAnnotated: [ 'AllowMagicNumber' ]
  ForbiddenComment:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: [ 'Preview' ]
  ThrowsCount:
    active: false
  ReturnCount:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
  MaxLineLength:
    maxLineLength: 150
    excludeCommentStatements: true

naming:
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  MatchingDeclarationName:
    active: false
  VariableNaming:
    active: false
  PackageNaming:
    packagePattern: '[a-z]+(\._?[_?A-Za-z0-9]*)*'
