name: Auto approve
on:
  pull_request:

jobs:
  bot-approve:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'bypass')

    permissions:
      pull-requests: write

    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v3.1.0
        with:
          review-message: 'Auto approve due to bypass label'
          github-token: ${{ secrets.SUNGBINLAND_BOT_TOKEN }}
